// swagger.js
import swaggerJSDoc from "swagger-jsdoc";
import { config } from "../utilities/config.js";
import { fileURLToPath } from "url";
import path from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const options = {
  definition: {
    openapi: "3.1.0",
    info: {
      title: "Dream team",
      version: "1.0.0",
      description: "Documentation generated by Scalar",
    },
    servers: [
      {
        url: config.URL,
      },
    ],
  },
  apis: [
    path.join(__dirname, "../entities/**/routes/*.js"),
  ],
};

const swaggerSpec = swaggerJSDoc(options);

export default swaggerSpec;
