export type TConfig = {
  DATABASE: string;
  USER: string;
  PASSWORD: string;
  HOST: string;
  JWT_ACCESS_SECRET: string;
  JWT_EXPIRES_IN: string;
  NODE_ENV: string;
  CORS_ORIGIN: string;
  PORT: string;
  URL: string;
  DB_PORT: string;
  PY_API: string;
  HACIENDA_API_SANDBOX: string;
  ENVIROMENT: string;
  HACIENDA_TOKEN: string;
  CERTIFICATE_PATH: string;
  CERTIFICATE_PASSWORD: string;
  TERMINAL: string;
};
