import type { TConfig } from "../domain/types/TConf.js";
import { env } from "./validator.js";

export const config: TConfig = {
  DATABASE: env.DATABASE,
  USER: env.USER,
  PASSWORD: env.PASSWORD,
  HOST: env.HOST,
  JWT_ACCESS_SECRET: env.JWT_ACCESS_SECRET,
  JWT_EXPIRES_IN: env.JWT_EXPIRES_IN,
  NODE_ENV: env.NODE_ENV,
  CORS_ORIGIN: env.CORS_ORIGIN,
  PORT: env.PORT,
  URL: env.URL,
  DB_PORT: env.DB_PORT,
  PY_API: env.PY_API,
  HACIENDA_API_SANDBOX: env.HACIENDA_API_SANDBOX,
  ENVIROMENT: env.ENVIROMENT,
  HACIENDA_TOKEN: env.HACIENDA_TOKEN,
  CERTIFICATE_PATH: env.CERTIFICATE_PATH,
  CERTIFICATE_PASSWORD: env.CERTIFICATE_PASSWORD,
};